CREATE TABLE IF NOT EXISTS "zfweb_address" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"add1" varchar(256) NOT NULL,
	"add2" varchar(256) NOT NULL,
	"add3" varchar(256) NOT NULL,
	"city" varchar(1024) NOT NULL,
	"state" varchar(256) NOT NULL,
	"zip" integer NOT NULL,
	"postcode" varchar(256),
	"province" varchar(256),
	"country" varchar(256) NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "zfweb_customer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"first_name" varchar(256) NOT NULL,
	"middle_name" varchar(256) NOT NULL,
	"last_name" varchar(256) NOT NULL,
	"email" varchar(1024) NOT NULL,
	"ph" integer NOT NULL,
	"is_user" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "zfweb_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"buyer_id" integer NOT NULL,
	"receiver_id" integer,
	"buyer_address_id" integer NOT NULL,
	"ship_address_id" integer NOT NULL,
	"description" varchar(1024) NOT NULL,
	"price" integer NOT NULL,
	"utkey" varchar(1024) NOT NULL,
	"url" varchar(1024) NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "zfweb_order_products" (
	"order_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"quantity" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "zfweb_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" varchar(1024) NOT NULL,
	"price" integer NOT NULL,
	"img_key_1" varchar(1024) NOT NULL,
	"img_url_1" varchar(1024) NOT NULL,
	"img_key_2" varchar(1024),
	"img_url_2" varchar(1024),
	"img_key_3" varchar(1024),
	"img_url_3" varchar(1024),
	"video_key" varchar(1024),
	"video_url" varchar(1024),
	"inventory" integer NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "zfweb_address" ADD CONSTRAINT "zfweb_address_customer_id_zfweb_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."zfweb_customer"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "zfweb_order" ADD CONSTRAINT "zfweb_order_buyer_id_zfweb_customer_id_fk" FOREIGN KEY ("buyer_id") REFERENCES "public"."zfweb_customer"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "zfweb_order" ADD CONSTRAINT "zfweb_order_receiver_id_zfweb_customer_id_fk" FOREIGN KEY ("receiver_id") REFERENCES "public"."zfweb_customer"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "zfweb_order" ADD CONSTRAINT "zfweb_order_buyer_address_id_zfweb_address_id_fk" FOREIGN KEY ("buyer_address_id") REFERENCES "public"."zfweb_address"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "zfweb_order" ADD CONSTRAINT "zfweb_order_ship_address_id_zfweb_address_id_fk" FOREIGN KEY ("ship_address_id") REFERENCES "public"."zfweb_address"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "zfweb_order_products" ADD CONSTRAINT "zfweb_order_products_order_id_zfweb_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."zfweb_order"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "zfweb_order_products" ADD CONSTRAINT "zfweb_order_products_product_id_zfweb_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."zfweb_product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_idx" ON "zfweb_product" USING btree ("title");